/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get events
         * @description Get events from database with optional filtering. Supports filtering by date range, types, groups, and disciplines.
         */
        get: operations["fetch_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch and save events
         * @description Fetch events from external source and save them to database. Fetches events from the climbing competition source with specified filters, checks for duplicates, and inserts new events into the database.
         */
        get: operations["fetch_events_remote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get teams
         * @description Get teams from the specified event by parsing the live results page. Finds the event 'Первенство России' with year 2025 and group 'Ю', then fetches and parses the live results page to extract team names. Returns cached data if available for the specified year.
         */
        get: operations["get_teams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root endpoint
         * @description Root endpoint for the API. Returns a welcome message with API version.
         */
        get: operations["root"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Health check endpoint. Returns API health status.
         */
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BaseResponse
         * @description Base response model for all API endpoints.
         */
        BaseResponse: {
            /** Success */
            success: boolean;
            /** Data */
            data?: unknown | null;
            /** Message */
            message?: string | null;
        };
        /** BaseResponse[List[EventResponse]] */
        BaseResponse_List_EventResponse__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["EventResponse"][] | null;
            /** Message */
            message?: string | null;
        };
        /** Body_fetch_events */
        Body_fetch_events: {
            /** Ranks */
            ranks?: string[] | null;
            /** Types */
            types?: string[] | null;
            /** Groups */
            groups?: string[] | null;
            /** Disciplines */
            disciplines?: string[] | null;
        };
        /** Body_fetch_events_remote */
        Body_fetch_events_remote: {
            /** Ranks */
            ranks?: string[] | null;
            /** Types */
            types?: string[] | null;
            /** Groups */
            groups?: string[] | null;
            /** Disciplines */
            disciplines?: string[] | null;
        };
        /** EventResponse */
        EventResponse: {
            /** Date */
            date: string;
            /** Year */
            year?: string | null;
            /** Rank */
            rank?: string | null;
            /** Startdate */
            startdate?: string | null;
            /** Enddate */
            enddate?: string | null;
            /** Link */
            link: string;
            /** Name */
            name: string;
            /** Location */
            location: string;
            /** Type */
            type: string;
            /** Groups */
            groups: string[];
            /** Disciplines */
            disciplines: string[];
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    fetch_events: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Body_fetch_events"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponse_List_EventResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_events_remote: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Body_fetch_events_remote"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_teams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponse"];
                };
            };
        };
    };
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponse"];
                };
            };
        };
    };
}
